<?php
$data = array (
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '女性用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => 4,
    'level' => 0,
    'id' => '52',
    'name' => '女性用品',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '仿真阳具',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '76',
    'name' => '仿真阳具',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '转珠棒',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '77',
    'name' => '转珠棒',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '多点按摩棒',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '75',
    'name' => '多点按摩棒',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '情趣内衣',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 3,
    'level' => 0,
    'id' => '65',
    'name' => '情趣内衣',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '男性用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 2,
    'level' => 0,
    'id' => '63',
    'name' => '男性用品',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '飞机杯',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '68',
    'name' => '飞机杯',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '女优名器',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '69',
    'name' => '女优名器',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '臀胸倒模',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '70',
    'name' => '臀胸倒模',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '助勃增大',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '71',
    'name' => '助勃增大',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '前列腺刺激',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '73',
    'name' => '前列腺刺激',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '充气娃娃',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '74',
    'name' => '充气娃娃',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '延时喷剂',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '72',
    'name' => '延时喷剂',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '安全避孕',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '78',
    'name' => '安全避孕',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '持久',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '79',
    'name' => '持久',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '情趣',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '83',
    'name' => '情趣',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '倍滑',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '80',
    'name' => '倍滑',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '其它',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '84',
    'name' => '其它',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '超薄',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '81',
    'name' => '超薄',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '紧型',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '82',
    'name' => '紧型',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '延时助情',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '64',
    'name' => '延时助情',
  ),
);
?>